savannahghi/onboarding

Dockerfile
cloudbuild.yaml

Automate deploy to Google Cloud Run with Cloud Build Trigger

feat: add Cloud Build Cloud Run deployement configuration

---

cloudbuild.yaml

fix: docker image tag

---

cloudbuild.yaml

fix: substitute docker build args in Cloud Build config

---

cloudbuild.yaml

chore: substitute secret name as cloud build enviroment variable

---

cloudbuild.yaml

chore: substitute secret name as cloud build enviroment variable (#8)

---

.github/scripts/decrypt_secret.sh
.github/workflows/codeql-analysis.yml

feat: add CodeQL analysis workflow

---

.github/issue_template.md
.github/pull_request_template.md
CONTRIBUTING.md
LICENSE

chore: add licence and other docs

---

.github/workflows/ci.yml
README.md

chore: update readme and add coveralls code coverage

---

go.mod
go.sum
pkg/onboarding/application/dto/input.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

chore: roles repository interface changes and tests

---

.github/workflows/ci.yml

chore: fix coverralls coverage budge

---

cloudbuild.yaml

feat: automatically update the traffic to the latest revision

---

pkg/onboarding/infrastructure/database/fb/firebase_integration_test.go
pkg/onboarding/infrastructure/services/edi/mock/service_mock.go
pkg/onboarding/infrastructure/services/edi/service.go
pkg/onboarding/infrastructure/services/edi/service_test.go
pkg/onboarding/infrastructure/services/engagement/mock/service_mock.go
pkg/onboarding/infrastructure/services/engagement/service.go
pkg/onboarding/presentation/config.go
pkg/onboarding/usecases/login_test.go
pkg/onboarding/usecases/supplier_internal_test.go
pkg/onboarding/usecases/ussd/main_integration_test.go
tests/config_test.go

Signed-off-by: Salaton <salaton@healthcloud.co.ke>

chore: update autolinking feature

---

go.mod
go.sum
pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_extension.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: add listing roles and permissions

---

pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_integration_test.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: assigning and revoking roles for users

---

.github/workflows/ci.yml
cloudbuild.yaml
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/infrastructure/services/edi/service_test.go
pkg/onboarding/usecases/admin/service_test.go
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/profile_integration_test.go
pkg/onboarding/usecases/profile_unit_test.go
pkg/onboarding/usecases/roles_unit_test.go
pkg/onboarding/usecases/signup.go
pkg/onboarding/usecases/ussd/main_integration_test.go
pkg/onboarding/usecases/ussd/register.go
pkg/onboarding/usecases/ussd/register_integration_test.go
pkg/onboarding/usecases/ussd/registration_unit_test.go

fix: ci testing and linting

---

go.sum
pkg/onboarding/application/dto/input.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/presentation/config.go
pkg/onboarding/presentation/graph/enums.graphql
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/presentation/rest/handlers_test.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/agent_unit_test.go
pkg/onboarding/usecases/login_test.go
pkg/onboarding/usecases/ussd/main_integration_test.go

- role is assigned during user creation i.e agent role
- remove mandatory email during user creation
- add flag to indicate whether to resend temporary pin for created user

feat: role assignment and optional email in user creation

---

pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go
pkg/onboarding/usecases/ussd/register_integration_test.go
tests/supplier_acceptance_test.go

feat: add revoking role permissions and deleting roles

---

pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: add searching of roles by name as a filter

---

pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/profile_integration_test.go
pkg/onboarding/usecases/profile_unit_test.go

feat: search for user using their phone number

---

pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: activating and deactivating roles

---

pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: update scopes for a role

---

pkg/onboarding/application/dto/output.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go

fix: nil primary email address when listing employees

---

pkg/onboarding/application/dto/input.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/agent_unit_test.go

feat: activating and deactivating employee/admin account

---

pkg/onboarding/application/common/common.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/application/utils/actions.go
pkg/onboarding/application/utils/actions_test.go
pkg/onboarding/application/utils/helpers.go
pkg/onboarding/domain/constants.go
pkg/onboarding/domain/models.go
pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/profile_unit_test.go

feat: add getting user navigation actions based on permissions

---

pkg/onboarding/application/common/common.go
pkg/onboarding/application/dto/input.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/application/utils/actions.go
pkg/onboarding/application/utils/actions_test.go
pkg/onboarding/application/utils/helpers.go
pkg/onboarding/domain/constants.go
pkg/onboarding/domain/models.go
pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/agent_unit_test.go
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/profile_integration_test.go
pkg/onboarding/usecases/profile_unit_test.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

feat: roles listing filter, activation and deactivation of roles, user search

---

pkg/onboarding/application/utils/helpers.go
pkg/onboarding/application/utils/helpers_test.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/login.go
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/profile_unit_test.go
pkg/onboarding/usecases/signup.go

feat: map new nav actions implementation to initial navactions

---

.github/workflows/ci.yml
cloudbuild.yaml
pkg/onboarding/presentation/rest/handlers_test.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/usecases/agent_unit_test.go
pkg/onboarding/usecases/login_unit_test.go
pkg/onboarding/usecases/profile_unit_test.go
pkg/onboarding/usecases/signup_unit_test.go

Signed-off-by: Calvine Otieno <calvine.otieno@healthcloud.co.ke>

feat: substitute revision cpu and memory limits as env vars

---

pkg/onboarding/application/common/common.go
pkg/onboarding/application/dto/input.go
pkg/onboarding/infrastructure/services/edi/mock/service_mock.go
pkg/onboarding/infrastructure/services/edi/service.go
pkg/onboarding/infrastructure/services/edi/service_test.go
pkg/onboarding/infrastructure/services/pubsub/mock/service_mock.go
pkg/onboarding/infrastructure/services/pubsub/publisher.go
pkg/onboarding/infrastructure/services/pubsub/service.go
pkg/onboarding/infrastructure/services/pubsub/subscriber.go

feat: autolink covers for sladers who receive an SMS from EDI

---

pkg/onboarding/usecases/profile_unit_test.go

test: fix tests for getting navigation actions usecase

---

pkg/onboarding/application/utils/helpers.go
pkg/onboarding/infrastructure/database/fb/firebase.go

chore: filter roles using filter input struct

---

pkg/onboarding/application/utils/actions.go
pkg/onboarding/application/utils/actions_test.go
pkg/onboarding/application/utils/helpers.go

fix: ensure that returned navigation actions are in the order required

---

pkg/onboarding/application/utils/admin_template.go
pkg/onboarding/application/utils/agent_template.go
pkg/onboarding/application/utils/kyc_email_templates.go

chore: update email templates

---

pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

fix: change role filter to search role by role name

---

pkg/onboarding/domain/constants.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

fix: return empty list for missing role in role search

chore: update registered user welcome message

---

.github/workflows/deployment.yaml

[ ] Build and push docker image to GCR
[ ] Deploy the revision to Cloud Run via CI
[ ] Make this workflow stage depend on CI test and lint workflow
- Any new files are updated in the folder structure in the …

feat: layout community onboarding service deployment

---

pkg/onboarding/infrastructure/database/fb/firebase.go

fix: flagged feature disabled on token refresh

---

pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_integration_test.go

refactor purge user not to fail to remove user is pin, customer and supplier profiles are not found

---

.github/workflows/deployment.yaml

[ ] Deploy test server to Google Cloud Run
[ ] Supply secrets via Google Secret Manager

feat: add service deployment job

---

.github/workflows/deployment.yaml

fix: set-env-vars for root collection suffix

---

.github/workflows/deployment.yaml

fix:  root collection and sentry dns env

---

pkg/onboarding/application/dto/input.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/domain/models.go
pkg/onboarding/infrastructure/database/fb/firebase.go
pkg/onboarding/infrastructure/database/fb/firebase_test.go
pkg/onboarding/presentation/config.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/inputs.graphql
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/presentation/graph/types.graphql
pkg/onboarding/presentation/rest/handlers_test.go
pkg/onboarding/repository/mock/onboarding.go
pkg/onboarding/repository/onboarding.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go
pkg/onboarding/usecases/agent.go
pkg/onboarding/usecases/agent_unit_test.go
pkg/onboarding/usecases/login_test.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go
pkg/onboarding/usecases/ussd/main_integration_test.go
tests/roles_acceptance_test.go

feat: add and save role revocation reason

---

go.sum
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/admin_unit_test.go

feat: add searching admin by phone

---

pkg/onboarding/application/dto/output.go
pkg/onboarding/domain/enum.go
pkg/onboarding/domain/enum_test.go
pkg/onboarding/infrastructure/services/engagement/mock/service_mock.go
pkg/onboarding/infrastructure/services/engagement/service.go
pkg/onboarding/infrastructure/services/engagement/service_unit_test.go
pkg/onboarding/presentation/graph/enums.graphql
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/user_pin.go
pkg/onboarding/usecases/user_pin_test.go

feat: resending temporary pin to users

---

.github/workflows/ci.yml

chore: add ci schema validation command

---

pkg/onboarding/presentation/rest/handlers.go
pkg/onboarding/presentation/rest/handlers_test.go
pkg/onboarding/usecases/roles.go
pkg/onboarding/usecases/roles_unit_test.go

chore: remove test roles

---

pkg/onboarding/application/dto/input.go
pkg/onboarding/application/dto/output.go
pkg/onboarding/presentation/config.go
pkg/onboarding/presentation/rest/handlers.go
pkg/onboarding/presentation/rest/handlers_test.go
pkg/onboarding/usecases/profile.go
pkg/onboarding/usecases/signup.go
pkg/onboarding/usecases/signup_unit_test.go

feat: add register user rest endpoint

---

pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go

AddPartnertype
SuspendSupplier
SuplierDefaultLocation
SuspendSupplier

chore: retire and remove nolonger used schema and mutations

---

pkg/onboarding/infrastructure/database/service.go
pkg/onboarding/infrastructure/infrastructure.go

chore: improve dependency injection role repository

---

pkg/onboarding/infrastructure/database/service.go
pkg/onboarding/infrastructure/infrastructure.go

chore: improve dependency injection in customer repository methods

---

pkg/onboarding/infrastructure/database/service.go
pkg/onboarding/infrastructure/infrastructure.go

chore: improve dependency injection in user profile repository

---

pkg/onboarding/application/utils/validators.go
pkg/onboarding/application/utils/validators_test.go
pkg/onboarding/presentation/rest/handlers.go
pkg/onboarding/usecases/signup.go

chore: add validator for register user input

---

pkg/onboarding/application/dto/output.go
pkg/onboarding/domain/enum.go
pkg/onboarding/domain/enum_test.go
pkg/onboarding/infrastructure/services/engagement/mock/service_mock.go
pkg/onboarding/infrastructure/services/engagement/service.go
pkg/onboarding/presentation/graph/enums.graphql
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/profile.graphql
pkg/onboarding/presentation/graph/profile.resolvers.go
pkg/onboarding/usecases/user_pin.go
pkg/onboarding/usecases/user_pin_test.go

feat: add sending temporary pin to users on demand

---

pkg/onboarding/infrastructure/database/service.go
pkg/onboarding/infrastructure/infrastructure.go

chore: user profile repository infrastructure interface

---

pkg/onboarding/infrastructure/database/fb/firebase_integration_test.go
pkg/onboarding/infrastructure/infrastructure.go
pkg/onboarding/infrastructure/services/pubsub/service.go
pkg/onboarding/presentation/config.go
pkg/onboarding/usecases/login_test.go
tests/config_test.go

add onboarding depedency injection

chore:onboarding depedency injection

---

pkg/onboarding/application/utils/actions_test.go
pkg/onboarding/domain/actions.go
pkg/onboarding/usecases/profile_unit_test.go

chore: add consumer registration route

---

pkg/onboarding/infrastructure/mock/infrastructure_mock.go
pkg/onboarding/usecases/profile.go

Signed-off-by: Kathurima Kimathi <kathurimakimathi415@gmail.com>

chore: add depedency injection mocks

---

pkg/onboarding/application/utils/actions_test.go
pkg/onboarding/domain/actions.go
pkg/onboarding/usecases/admin.go
pkg/onboarding/usecases/profile_unit_test.go

fix: add required permission to consumer navigation action

---

go.sum
pkg/onboarding/presentation/graph/entity.resolvers.go
pkg/onboarding/presentation/graph/generated/ast.go
pkg/onboarding/presentation/graph/generated/federation.go
pkg/onboarding/presentation/graph/generated/generated.go
pkg/onboarding/presentation/graph/types.graphql

chore: expose generated ast sources

---

pkg/onboarding/usecases/roles.go

fix: update existing role when creating an unauthorized role
